schemaVersion: f8serviceEntry/1
serviceClass: f8.cvkit.denseoptflow
label: CVKit Dense Optical Flow
version: 0.0.1
launch:
  command: pixi
  args:
    - run
    - -e
    - default
    - python
    - scripts/run_cpp_service.py
    - --service-dir
    - services/f8/cvkit/dense_optflow
    - --exe
    - f8cvkit_dense_optflow_service
    - --env-var
    - F8CVKIT_DENSE_OPTFLOW_EXE
  env: {}
  workdir: "../../../../"
