[project]
name = "f8pymppose"
version = "0.1.0"
description = "MediaPipe Pose service for Feel8."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "f8pysdk",
    "numpy>=2.2.0",
    "opencv-contrib-python>=4.10.0",
    "mediapipe>=0.10.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["f8pymppose"]

[tool.uv]
package = true
