[project]
name = "f8pyengine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "buttplug>=1.0.0",
    "nats-py>=2.12.0",
    "numpy>=1.26.0",
    "scipy>=1.14.0",
    "pyserial>=3.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["f8pyengine"]

[tool.uv]
package = true
