schemaVersion: f8serviceEntry/1
serviceClass: f8/engine
label: Engine
version: 0.0.1
launch:
  command: uv
  args: ["run", "python", "-m", "f8pyengineqt.engine.engine_service_process"]
  env: {}
  workdir: "../../../"
