[project]
name = "f8pysdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datamodel-code-generator[ruff]>=0.50.0",
    "nats-py>=2.12.0",
]

[build-system]
requires = ["hatchling", "datamodel-code-generator[ruff]>=0.50.0"]
build-backend = "hatchling.build"

[tool.hatch.build]
ignore-vcs = true

[tool.hatch.build.targets.wheel]
packages = ["f8pysdk", "f8pysdk.generated"]

[tool.hatch.build.hooks.custom]
path = "build_hooks.py"

[tool.uv]
package = true
