schemaVersion: f8serviceEntry/1
serviceClass: f8.templatetracker
label: Template Tracker
version: 0.0.1
launch:
  command: pixi
  args: ["run", "-e", "onnx", "template_tracker"]
  env: {}
  workdir: "../../../"
