schemaVersion: f8serviceEntry/1
serviceClass: f8.dl.humandetector
label: DL Human Detector
version: 0.0.1
launch:
  command: pixi
  args: ["run", "-e", "onnx", "dl_humandetector"]
  env: {}
  workdir: "../../../../"
