[project]
name = "f8pystudio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qtpy>=2.4.3",
    "pyside6>=6.10.1",
    "setuptools",
    "nodegraphqt>=0.6.43",
    "pyqtgraph>=0.14.0",
    "nats-py>=2.12.0",
    "datamodel-code-generator>=0.50.0",
    "shortuuid>=1.0.13",
    "qtawesome>=1.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["f8pystudio"]
include = [
    "f8pystudio/render_nodes/web_assets/**/*.html",
    "f8pystudio/render_nodes/web_assets/**/*.js",
]

[tool.uv]
package = true
