schemaVersion: f8serviceEntry/1
serviceClass: f8.detecttracker
label: Detect Tracker
version: 0.0.1
launch:
  command: pixi
  args: ["run", "-e", "onnx", "detect_tracker"]
  env: {}
  workdir: "../../../"

