schemaVersion: f8serviceEntry/1
serviceClass: f8.cvkit.videostab
label: CVKit Video Stabilizer
version: 0.0.1
launch:
  command: pixi
  args:
    - run
    - -e
    - default
    - python
    - scripts/run_cpp_service.py
    - --service-dir
    - services/f8/cvkit/video_stab
    - --exe
    - f8cvkit_video_stab_service
    - --env-var
    - F8CVKIT_VIDEO_STAB_EXE
  env: {}
  workdir: "../../../../"
